### ISSUE TITLE
при создании класса CrossWebTask нет передачи аргументов в self.cats

### ISSUE THREAD

**Issue by 888joker** [MEDIASCOPE-JSC/mediascope-api-lib#1]
Кажется в этом классе должно быть так:
`self.cats = catalogs.CrossWebCats(settings_filename=settings_filename, cache_path=cache_path)`
потому что есть интерфейс передачи этих параметров в сам класс CrossWebTask:
`def __init__(self, settings_filename=None, cache_path=None, *args, **kwargs): ...`
 => подразумевается опциональность создания\не создания settings.json в корне проекта (что может быть очень неудобным для существующих проектов, т.к. там уже может быть файл с идентичным названием, но с другими целями).  
А сейчас получается так, что пользователям модуля не остается выбора: класс CrossWebCats возможно использовать без этого файла в корне, а класс CrossWebTask уже нельзя (будет ошибка No such file or directory: 'settings.json') .

**Comment by Mediascope-net** [comment]
Исправлено в v1.1.15
